# Generated by Django 3.1 on 2021-06-02 07:58

from django.db import migrations, models
import django.db.models.deletion
import projeto.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='Name', max_length=128, verbose_name='Name')),
                ('SurName', models.CharField(default='Sur Name', max_length=128, verbose_name='Sur Name')),
                ('Email', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(default='Question', max_length=1024, verbose_name='Question')),
                ('Answer', models.CharField(default='Answer', max_length=1024, verbose_name='Answer')),
            ],
            options={
                'verbose_name': 'Quiz Question/Answer',
                'verbose_name_plural': 'Quiz Question/Answer',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.FloatField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.contact')),
            ],
            options={
                'verbose_name': 'Result',
                'verbose_name_plural': 'Results',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Likeness', models.CharField(default='100', max_length=3, verbose_name='From 0 to 100, how much did you like this game?')),
                ('GamePlayComment', models.TextField(default=' ', max_length=5000, verbose_name='In terms of gameplay, what did you think?')),
                ('Opinion', models.TextField(default=' ', max_length=5000, verbose_name='Leave your opinions here.')),
                ('File', models.FileField(upload_to='useruploadedfiles/%Y/%m/%d', validators=[projeto.validators.validate_file_extension], verbose_name='Any more complex suggestions submit via .txt file')),
                ('Recommend', models.BooleanField(default=True, verbose_name='Would you recommend this game to your friends?')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.contact')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
