# Generated by Django 3.1 on 2021-06-02 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score', models.CharField(default=100, max_length=4)),
                ('Primary', models.CharField(default=' ', max_length=128)),
                ('Secondary', models.CharField(default=' ', max_length=128)),
                ('Text', models.CharField(default=' ', max_length=128)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.contact')),
            ],
            options={
                'verbose_name': 'Website Suggestion',
                'verbose_name_plural': 'Website Suggestions',
            },
        ),
    ]
