# Generated by Django 3.1 on 2021-06-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='ChoiceFour',
            field=models.CharField(default='ChoiceFour', max_length=128, verbose_name='Choice'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='ChoiceOne',
            field=models.CharField(default='ChoiceOne', max_length=128, verbose_name='Choice'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='ChoiceThree',
            field=models.CharField(default='ChoiceThree', max_length=128, verbose_name='Choice'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='ChoiceTwo',
            field=models.CharField(default='ChoiceTwo', max_length=128, verbose_name='Choice'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='Type',
            field=models.CharField(choices=[('choice', 'choice'), ('input', 'input')], default='choice', max_length=6),
        ),
        migrations.AlterField(
            model_name='suggestions',
            name='Score',
            field=models.CharField(default=100, max_length=4, verbose_name='From 0 to 100, how much did you like this website?'),
        ),
    ]
