# Generated by Django 3.1 on 2021-06-03 14:51

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0003_auto_20210602_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='DateOfBirth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='contact',
            name='Phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+41524204242', max_length=128, region=None),
        ),
    ]
