# Generated by Django 3.2.4 on 2021-06-04 14:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0005_auto_20210604_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='Email',
            field=models.EmailField(default='exemplo@exemplo.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Name',
            field=models.CharField(default='Nome', max_length=128, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+351961234567', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='contact',
            name='SurName',
            field=models.CharField(default='Apelido', max_length=128, verbose_name='Apelido'),
        ),
    ]
