# Generated by Django 3.2.4 on 2021-06-04 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0006_auto_20210604_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='Answer',
            field=models.CharField(default='Resposta', max_length=1024, verbose_name='Resposta'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='ChoiceFour',
            field=models.CharField(default='4ºEscolha', max_length=128, verbose_name='Escolha'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='ChoiceOne',
            field=models.CharField(default='1ºEscolha', max_length=128, verbose_name='Escolha'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='ChoiceThree',
            field=models.CharField(default='3ºEscolha', max_length=128, verbose_name='Escolha'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='ChoiceTwo',
            field=models.CharField(default='2ºEscolha', max_length=128, verbose_name='Escolha'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='Question',
            field=models.CharField(default='Questão', max_length=1024, verbose_name='Questão'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='Type',
            field=models.CharField(choices=[('choice', 'choice'), ('input', 'input')], default='Escolha', max_length=6),
        ),
    ]
