# Generated by Django 3.2.4 on 2021-06-04 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0007_auto_20210604_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Quiz Pergunta/Resposta', 'verbose_name_plural': 'Quiz Pergunta/Resposta'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': 'Resultado', 'verbose_name_plural': 'Resultados'},
        ),
    ]
