# Generated by Django 3.2.4 on 2021-06-04 14:55

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0008_auto_20210604_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='DateOfBirth',
            field=models.DateField(default=datetime.date.today, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='Phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+351961234567', max_length=128, region=None, verbose_name='Contacto'),
        ),
    ]
