# Generated by Django 3.2.4 on 2021-06-04 15:15

from django.db import migrations, models
import projeto.validators


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0009_auto_20210604_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Comentário', 'verbose_name_plural': 'Comentários'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contacto', 'verbose_name_plural': 'Contactos'},
        ),
        migrations.AlterModelOptions(
            name='suggestions',
            options={'verbose_name': 'SugestãoWebsite', 'verbose_name_plural': 'SugestõesWebsite'},
        ),
        migrations.AlterField(
            model_name='comment',
            name='File',
            field=models.FileField(upload_to='useruploadedfiles/%Y/%m/%d', validators=[projeto.validators.validate_file_extension], verbose_name='Qualquer sugestão mais complexa submeta via ficheiro .txt'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='GamePlayComment',
            field=models.TextField(default=' ', max_length=5000, verbose_name='Em termos de jogabilidade o que achou?'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Likeness',
            field=models.CharField(default='100', max_length=3, verbose_name='De 0 a 100, quanto gostou deste jogo?'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Opinion',
            field=models.TextField(default=' ', max_length=5000, verbose_name='Deixe aqui as suas opiniões.'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Recommend',
            field=models.BooleanField(default=True, verbose_name='Recomendariam este jogo aos seus amigos?'),
        ),
        migrations.AlterField(
            model_name='suggestions',
            name='Score',
            field=models.CharField(default=100, max_length=4, verbose_name='De 0 a 100, quanto gostaram deste website?'),
        ),
    ]
